name: Deploy anubis-eye-v6thoth

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: pip install fastapi uvicorn
      - run: uvicorn thoth_core.main:app --host 0.0.0.0 --port ${{ secrets.PORT }}
